# Generated by Django 5.0.1 on 2024-01-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0002_rename_movies_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=30)),
                ('cast', models.CharField(max_length=300)),
                ('seasons', models.IntegerField()),
                ('episodes', models.IntegerField()),
            ],
        ),
    ]
