# Generated by Django 5.0.1 on 2024-01-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0003_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('finished', 'Finished')], default='ongoing', max_length=10),
        ),
    ]
