# Generated by Django 5.0.1 on 2024-01-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0004_series_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='director',
            new_name='creators',
        ),
        migrations.AddField(
            model_name='series',
            name='image',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='series',
            name='genre',
            field=models.CharField(max_length=100),
        ),
    ]
