# Generated by Django 5.0.1 on 2024-01-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0006_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='avearge_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='avearge_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='avearge_rating',
            field=models.FloatField(default=0),
        ),
    ]
